import Link from 'next/link'
import styles from './Navigation.module.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

const links = [{
  label: 'Home',
  route: '/'
},
{
  label: 'pokemon',
  route: '/pokemon'
}, {
  label: 'About',
  route: '/about'
}, {
  label: 'Stats',
  route: '/stats'
}, {
  label: 'TierList',
  route: '/tier'
}, {
  label: 'Builder',
  route: '/builder'
}, {
  label: 'Items',
  route: '/objetos'
}, {
  label: 'Emblems',
  route: '/medallas'
}, {
  label: 'post',
  route: '/posts'
}]

export function Navigation () {
  return (
    <header className={styles.header}>
      <nav>
        <ul className={styles.navigation}>
          {links.map(({ label, route }) => (
            <li key={route}>
              <Link href={route}>
                {label}
              </Link>
            </li>
          )
          )}
        </ul>
      </nav>
    </header>
  )
}
